kind = "web"
previewPath = "/"
title = "Arduino Tutorials"
version = "1.0.0"
id = "artifacts/arduino-tutorials"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
localPort = 23791
name = "web"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/arduino-tutorials run dev"

[services.env]
PORT = "23791"
BASE_PATH = "/"

[services.production]
build = ["pnpm", "--filter", "@workspace/arduino-tutorials", "run", "build"]
publicDir = "artifacts/arduino-tutorials/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"
